import json
import os
import time
from datetime import datetime

# Paths
BRIDGE_DIR = "bot/broker/mt5_bridge"
STATUS_FILE = os.path.join(BRIDGE_DIR, "status.json")
COMMAND_DIR = os.path.join(BRIDGE_DIR, "Command")

def load_status():
    """Reads the status.json generated by the EA."""
    if not os.path.exists(STATUS_FILE):
        print(f"❌ Status file not found at {STATUS_FILE}")
        return None
    
    try:
        with open(STATUS_FILE, "r") as f:
            return json.load(f)
    except json.JSONDecodeError:
        print("❌ Error decoding status.json")
        return None

def send_close_command(ticket, symbol):
    """Sends a CLOSE command for a specific ticket."""
    command = {
        "action": "CLOSE",
        "ticket": ticket,
        "symbol": symbol,
        "magic": 0,
        "comment": "Auto-Cleanup Unauthorized Pilot"
    }
    
    timestamp = int(time.time() * 1000)
    filename = f"cmd_close_{ticket}_{timestamp}.json"
    filepath = os.path.join(COMMAND_DIR, filename)
    
    with open(filepath, "w") as f:
        json.dump(command, f)
    
    print(f"🚀 Sent CLOSE command for Ticket {ticket} ({symbol})")

def main():
    print("🕵️‍♂️ Starting Pilot Check...")
    data = load_status()
    
    if not data or "positions" not in data:
        print("✅ No active positions found (or status empty).")
        return

    positions = data["positions"]
    authorized_count = 0
    unauthorized_count = 0
    
    print(f"📊 Found {len(positions)} open positions.")
    
    for pos in positions:
        ticket = pos.get("ticket")
        symbol = pos.get("symbol")
        volume = float(pos.get("vol", 0.0) or pos.get("volume", 0.0))
        profit = float(pos.get("profit", 0.0))
        
        # RULE: Python Bot only trades 0.10. anything else (like 0.01) is the EA.
        # Allowing a small margin for float comparison or manual intervention? 
        # No, let's be strict: < 0.09 is definitely a mistake.
        if volume < 0.09:
            print(f"⚠️  UNAUTHORIZED TRADE DETECTED: {symbol} | Vol: {volume} | Profit: {profit}")
            send_close_command(ticket, symbol)
            unauthorized_count += 1
        else:
            print(f"✅ Authorized Trade: {symbol} | Vol: {volume}")
            authorized_count += 1
            
    if unauthorized_count > 0:
        print(f"\n🧹 Cleanup Complete: {unauthorized_count} unauthorized trades targeted for closure.")
    else:
        print("\n✅ System Clean: No unauthorized trades found.")

if __name__ == "__main__":
    main()
